import { Service, Stat, TrustedCompany, WhyChooseItem, TechCategory, Industry, ProcessStep, PortfolioProject, Testimonial, TeamMember, FAQ, BlogPost, CareerPosition, Award, NavItem } from '@/types'

export const COMPANY_INFO = {
  name: 'QuickMindsSolutions',
  shortName: 'QMS',
  tagline: 'We Build Digital Solutions That Drive Business Growth',
  description:
    'A premier IT solutions company specializing in enterprise-grade software development, cloud solutions, AI integration, and digital transformation for businesses worldwide.',
  email: 'hello@quickmindssolutions.com',
  salesEmail: 'sales@quickmindssolutions.com',
  phone: '+1 (555) 123-4567',
  address: '123 Innovation Drive, Suite 400, San Francisco, CA 94105, USA',
  founded: '2013',
  linkedin: 'https://linkedin.com/company/quickmindssolutions',
  twitter: 'https://twitter.com/quickmindssolutions',
  github: 'https://github.com/quickmindssolutions',
  facebook: 'https://facebook.com/quickmindssolutions',
  instagram: 'https://instagram.com/quickmindssolutions',
  youtube: 'https://youtube.com/@quickmindssolutions',
}

export const NAV_ITEMS: NavItem[] = [
  { label: 'Home', href: '/' },
  {
    label: 'Services',
    href: '/services',
    children: [
      { label: 'Web Development', href: '/services/web-development' },
      { label: 'Mobile App Development', href: '/services/mobile-app-development' },
      { label: 'UI/UX Design', href: '/services/ui-ux-design' },
      { label: 'Cloud Solutions', href: '/services/cloud-solutions' },
      { label: 'AI & ML Solutions', href: '/services/ai-solutions' },
      { label: 'DevOps', href: '/services/devops' },
      { label: 'Data Engineering', href: '/services/data-engineering' },
      { label: 'QA Automation', href: '/services/qa-automation' },
    ],
  },
  {
    label: 'Solutions',
    href: '/solutions',
    children: [
      { label: 'Digital Transformation', href: '/solutions/digital-transformation' },
      { label: 'ERP Solutions', href: '/solutions/erp' },
      { label: 'E-Commerce', href: '/solutions/e-commerce' },
      { label: 'Software Consulting', href: '/solutions/consulting' },
    ],
  },
  { label: 'Industries', href: '/industries' },
  { label: 'Portfolio', href: '/portfolio' },
  { label: 'About', href: '/about' },
  { label: 'Careers', href: '/careers' },
  { label: 'Blog', href: '/blog' },
  { label: 'Contact', href: '/contact' },
]

export const STATS: Stat[] = [
  { value: 500, suffix: '+', label: 'Projects Delivered', icon: 'Briefcase' },
  { value: 150, suffix: '+', label: 'Happy Clients', icon: 'Users' },
  { value: 12, suffix: '+', label: 'Years Experience', icon: 'Calendar' },
  { value: 98, suffix: '%', label: 'Client Satisfaction', icon: 'ThumbsUp' },
]

export const TRUSTED_COMPANIES: TrustedCompany[] = [
  { name: 'NovaTech Corp', initials: 'NT', color: '#2563EB' },
  { name: 'Apex Digital', initials: 'AD', color: '#7C3AED' },
  { name: 'Horizon Labs', initials: 'HL', color: '#059669' },
  { name: 'CloudPeak Inc', initials: 'CP', color: '#DC2626' },
  { name: 'DataSphere', initials: 'DS', color: '#D97706' },
  { name: 'InnoVault', initials: 'IV', color: '#0891B2' },
  { name: 'MegaSoft', initials: 'MS', color: '#4F46E5' },
  { name: 'TrueScale', initials: 'TS', color: '#BE185D' },
  { name: 'BrightEdge', initials: 'BE', color: '#065F46' },
  { name: 'Quantum AI', initials: 'QA', color: '#7E22CE' },
  { name: 'PeakFlow', initials: 'PF', color: '#B45309' },
  { name: 'CoreLogic', initials: 'CL', color: '#1D4ED8' },
]

export const SERVICES: Service[] = [
  {
    id: 'web-development',
    slug: 'web-development',
    icon: 'Globe',
    title: 'Web Development',
    shortDesc: 'Scalable, high-performance web applications.',
    description:
      'We build robust, scalable, and high-performance web applications using cutting-edge frameworks. From SPAs to enterprise portals, we deliver exceptional digital experiences.',
    color: '#2563EB',
    gradient: 'from-blue-600 to-blue-400',
    features: ['React & Next.js', 'Node.js & Express', 'REST & GraphQL APIs', 'PWA Development', 'Micro-frontends', 'Performance Optimization'],
  },
  {
    id: 'mobile-app-development',
    slug: 'mobile-app-development',
    icon: 'Smartphone',
    title: 'Mobile App Development',
    shortDesc: 'Cross-platform & native mobile apps.',
    description:
      'Create stunning, feature-rich mobile applications for iOS and Android. We use React Native and Flutter for cross-platform or Swift/Kotlin for native performance.',
    color: '#7C3AED',
    gradient: 'from-violet-600 to-purple-400',
    features: ['React Native', 'Flutter', 'iOS (Swift)', 'Android (Kotlin)', 'App Store Deployment', 'Push Notifications'],
  },
  {
    id: 'ui-ux-design',
    slug: 'ui-ux-design',
    icon: 'Palette',
    title: 'UI/UX Design',
    shortDesc: 'User-centric designs that convert.',
    description:
      'Our design team creates beautiful, intuitive interfaces backed by user research and data. We craft experiences that delight users and drive business metrics.',
    color: '#EC4899',
    gradient: 'from-pink-500 to-rose-400',
    features: ['User Research', 'Wireframing', 'Prototyping', 'Design Systems', 'Usability Testing', 'Figma & Adobe XD'],
  },
  {
    id: 'cloud-solutions',
    slug: 'cloud-solutions',
    icon: 'Cloud',
    title: 'Cloud Solutions',
    shortDesc: 'Scalable cloud infrastructure & migration.',
    description:
      'Leverage the full power of cloud computing with our AWS, Azure, and GCP expertise. We architect, migrate, and optimize cloud infrastructure for maximum performance.',
    color: '#0891B2',
    gradient: 'from-cyan-600 to-sky-400',
    features: ['AWS & Azure & GCP', 'Cloud Migration', 'Serverless Architecture', 'Kubernetes & Docker', 'Cost Optimization', '24/7 Monitoring'],
  },
  {
    id: 'ai-solutions',
    slug: 'ai-solutions',
    icon: 'Brain',
    title: 'AI & ML Solutions',
    shortDesc: 'Intelligent automation & AI-powered products.',
    description:
      'Harness artificial intelligence to automate processes, gain insights, and build smarter products. We implement ML models, NLP, computer vision, and generative AI solutions.',
    color: '#059669',
    gradient: 'from-emerald-600 to-green-400',
    features: ['Machine Learning', 'Natural Language Processing', 'Computer Vision', 'Generative AI', 'Predictive Analytics', 'AI Chatbots'],
  },
  {
    id: 'devops',
    slug: 'devops',
    icon: 'Settings',
    title: 'DevOps',
    shortDesc: 'CI/CD pipelines & infrastructure automation.',
    description:
      'Accelerate your delivery pipeline with modern DevOps practices. We set up robust CI/CD pipelines, infrastructure as code, and observability platforms.',
    color: '#D97706',
    gradient: 'from-amber-600 to-yellow-400',
    features: ['CI/CD Pipelines', 'Kubernetes', 'Docker Containers', 'Infrastructure as Code', 'GitHub Actions', 'Azure DevOps'],
  },
  {
    id: 'digital-transformation',
    slug: 'digital-transformation',
    icon: 'TrendingUp',
    title: 'Digital Transformation',
    shortDesc: 'End-to-end business modernization.',
    description:
      'Transform your legacy systems and business processes into modern, digital-first operations. We guide enterprises through every phase of their digital transformation journey.',
    color: '#DC2626',
    gradient: 'from-red-600 to-orange-400',
    features: ['Legacy Modernization', 'Process Automation', 'Digital Strategy', 'Change Management', 'Technology Roadmap', 'ROI Measurement'],
  },
  {
    id: 'data-engineering',
    slug: 'data-engineering',
    icon: 'Database',
    title: 'Data Engineering',
    shortDesc: 'Data pipelines, warehousing & analytics.',
    description:
      'Build powerful data infrastructure that turns raw data into business intelligence. We design data lakes, ETL pipelines, and real-time analytics platforms.',
    color: '#4F46E5',
    gradient: 'from-indigo-600 to-blue-400',
    features: ['Data Pipelines', 'Data Warehousing', 'ETL/ELT', 'Real-time Analytics', 'Power BI & Tableau', 'Apache Spark'],
  },
  {
    id: 'api-development',
    slug: 'api-development',
    icon: 'Code',
    title: 'API Development',
    shortDesc: 'Robust, scalable API integrations.',
    description:
      'Design and build high-performance, secure APIs that power your applications and enable seamless integrations. We follow OpenAPI standards and best practices.',
    color: '#0284C7',
    gradient: 'from-sky-600 to-cyan-400',
    features: ['REST APIs', 'GraphQL', 'WebSockets', 'API Gateway', 'OAuth 2.0', 'API Documentation'],
  },
  {
    id: 'software-consulting',
    slug: 'software-consulting',
    icon: 'MessageSquare',
    title: 'Software Consulting',
    shortDesc: 'Expert technology strategy & advisory.',
    description:
      'Get strategic technology guidance from our senior architects and consultants. We help you make informed technology decisions that align with your business goals.',
    color: '#7E22CE',
    gradient: 'from-purple-700 to-violet-500',
    features: ['Architecture Review', 'Tech Stack Selection', 'Code Audit', 'Scalability Planning', 'Team Augmentation', 'CTO-as-a-Service'],
  },
  {
    id: 'qa-automation',
    slug: 'qa-automation',
    icon: 'CheckCircle',
    title: 'QA Automation',
    shortDesc: 'Automated testing for quality assurance.',
    description:
      'Ensure software quality with comprehensive testing strategies. We implement automated test suites that catch bugs early and ensure rock-solid releases.',
    color: '#065F46',
    gradient: 'from-teal-600 to-emerald-400',
    features: ['Selenium & Playwright', 'API Testing', 'Performance Testing', 'Security Testing', 'CI Integration', 'Test Reporting'],
  },
  {
    id: 'erp-solutions',
    slug: 'erp-solutions',
    icon: 'BarChart',
    title: 'ERP Solutions',
    shortDesc: 'Custom & integrated ERP implementations.',
    description:
      'Streamline your business operations with custom ERP implementations. We integrate and customize enterprise solutions that unify your entire business workflow.',
    color: '#B45309',
    gradient: 'from-orange-600 to-amber-400',
    features: ['SAP Integration', 'Microsoft Dynamics', 'Custom ERP Build', 'Module Integration', 'Data Migration', 'Training & Support'],
  },
]

export const WHY_CHOOSE_US: WhyChooseItem[] = [
  {
    icon: 'Users',
    title: 'Experienced Team',
    description: '200+ certified engineers with deep expertise in cutting-edge technologies and industry best practices.',
    color: '#2563EB',
  },
  {
    icon: 'Zap',
    title: 'Agile Process',
    description: 'Iterative development with 2-week sprints, daily standups, and continuous delivery for faster time-to-market.',
    color: '#F59E0B',
  },
  {
    icon: 'DollarSign',
    title: 'Transparent Pricing',
    description: 'No hidden costs. Clear, competitive pricing with detailed proposals and regular budget reporting.',
    color: '#10B981',
  },
  {
    icon: 'Headphones',
    title: 'Dedicated Support',
    description: '24/7 post-launch support with SLA guarantees. Your success is our ongoing commitment.',
    color: '#EC4899',
  },
  {
    icon: 'Cpu',
    title: 'Modern Technologies',
    description: 'We stay ahead of the curve, constantly adopting proven modern technologies that give you a competitive edge.',
    color: '#8B5CF6',
  },
  {
    icon: 'Rocket',
    title: 'Fast Delivery',
    description: 'Efficient processes and experienced teams ensure on-time delivery without compromising on quality.',
    color: '#0891B2',
  },
  {
    icon: 'Shield',
    title: 'Secure Applications',
    description: 'Security-first development with OWASP compliance, penetration testing, and regular security audits.',
    color: '#DC2626',
  },
  {
    icon: 'Layers',
    title: 'Scalable Architecture',
    description: 'Solutions built to grow with your business — from startup MVP to enterprise scale, seamlessly.',
    color: '#D97706',
  },
]

export const TECH_CATEGORIES: TechCategory[] = [
  {
    id: 'frontend',
    label: 'Frontend',
    items: [
      { name: 'React', color: '#61DAFB' },
      { name: 'Next.js', color: '#000000' },
      { name: 'Angular', color: '#DD0031' },
      { name: 'Vue.js', color: '#4FC08D' },
      { name: 'TypeScript', color: '#3178C6' },
      { name: 'Tailwind CSS', color: '#06B6D4' },
    ],
  },
  {
    id: 'backend',
    label: 'Backend',
    items: [
      { name: 'Node.js', color: '#339933' },
      { name: '.NET', color: '#512BD4' },
      { name: 'Java', color: '#ED8B00' },
      { name: 'Python', color: '#3776AB' },
      { name: 'PHP', color: '#777BB4' },
      { name: 'Go', color: '#00ADD8' },
    ],
  },
  {
    id: 'database',
    label: 'Database',
    items: [
      { name: 'SQL Server', color: '#CC2927' },
      { name: 'PostgreSQL', color: '#4169E1' },
      { name: 'MongoDB', color: '#47A248' },
      { name: 'Redis', color: '#DC382D' },
      { name: 'MySQL', color: '#4479A1' },
      { name: 'Elasticsearch', color: '#005571' },
    ],
  },
  {
    id: 'cloud',
    label: 'Cloud',
    items: [
      { name: 'AWS', color: '#FF9900' },
      { name: 'Azure', color: '#0078D4' },
      { name: 'Google Cloud', color: '#4285F4' },
      { name: 'Firebase', color: '#FFCA28' },
      { name: 'Vercel', color: '#000000' },
      { name: 'Netlify', color: '#00C7B7' },
    ],
  },
  {
    id: 'devops',
    label: 'DevOps',
    items: [
      { name: 'Docker', color: '#2496ED' },
      { name: 'Kubernetes', color: '#326CE5' },
      { name: 'GitHub Actions', color: '#2088FF' },
      { name: 'Azure DevOps', color: '#0078D7' },
      { name: 'Terraform', color: '#7B42BC' },
      { name: 'Jenkins', color: '#D33833' },
    ],
  },
  {
    id: 'mobile',
    label: 'Mobile',
    items: [
      { name: 'React Native', color: '#61DAFB' },
      { name: 'Flutter', color: '#02569B' },
      { name: 'Swift', color: '#FA7343' },
      { name: 'Kotlin', color: '#7F52FF' },
      { name: 'Expo', color: '#000020' },
      { name: 'Ionic', color: '#3880FF' },
    ],
  },
]

export const INDUSTRIES: Industry[] = [
  { id: 'healthcare', icon: 'Heart', title: 'Healthcare', description: 'HIPAA-compliant telehealth, EMR, and patient management platforms.', color: '#DC2626', gradient: 'from-red-500 to-rose-400' },
  { id: 'finance', icon: 'TrendingUp', title: 'Finance & Banking', description: 'Secure fintech apps, payment gateways, and trading platforms.', color: '#2563EB', gradient: 'from-blue-600 to-blue-400' },
  { id: 'education', icon: 'BookOpen', title: 'Education', description: 'E-learning platforms, LMS systems, and virtual classroom solutions.', color: '#7C3AED', gradient: 'from-violet-600 to-purple-400' },
  { id: 'retail', icon: 'ShoppingCart', title: 'Retail & E-Commerce', description: 'Omnichannel commerce platforms and personalized shopping experiences.', color: '#D97706', gradient: 'from-amber-500 to-yellow-400' },
  { id: 'manufacturing', icon: 'Factory', title: 'Manufacturing', description: 'IoT-enabled smart factory, ERP, and supply chain optimization.', color: '#059669', gradient: 'from-emerald-600 to-green-400' },
  { id: 'logistics', icon: 'Truck', title: 'Logistics', description: 'Fleet management, route optimization, and warehouse automation.', color: '#0891B2', gradient: 'from-cyan-600 to-sky-400' },
  { id: 'hospitality', icon: 'Hotel', title: 'Hospitality', description: 'Hotel PMS, booking engines, and guest experience platforms.', color: '#EC4899', gradient: 'from-pink-500 to-rose-400' },
  { id: 'insurance', icon: 'Shield', title: 'Insurance', description: 'Policy management, claims processing, and InsurTech platforms.', color: '#4F46E5', gradient: 'from-indigo-600 to-blue-400' },
  { id: 'government', icon: 'Landmark', title: 'Government', description: 'Citizen services portals, smart city, and compliance platforms.', color: '#1D4ED8', gradient: 'from-blue-700 to-indigo-500' },
  { id: 'real-estate', icon: 'Building', title: 'Real Estate', description: 'Property management, virtual tours, and CRM platforms.', color: '#B45309', gradient: 'from-orange-600 to-amber-400' },
  { id: 'travel', icon: 'Plane', title: 'Travel & Tourism', description: 'Booking engines, itinerary planners, and travel marketplaces.', color: '#0284C7', gradient: 'from-sky-600 to-cyan-400' },
  { id: 'telecom', icon: 'Radio', title: 'Telecommunications', description: 'BSS/OSS systems, network management, and billing platforms.', color: '#7E22CE', gradient: 'from-purple-700 to-violet-500' },
]

export const PROCESS_STEPS: ProcessStep[] = [
  { step: 1, title: 'Discovery', description: 'Deep dive into your business goals, technical requirements, and user needs to define project scope.', icon: 'Search', color: '#2563EB' },
  { step: 2, title: 'Planning', description: 'Architecture design, technology selection, sprint planning, and resource allocation for project success.', icon: 'Map', color: '#7C3AED' },
  { step: 3, title: 'UI/UX Design', description: 'Wireframes, prototypes, and pixel-perfect designs reviewed and approved before development begins.', icon: 'Palette', color: '#EC4899' },
  { step: 4, title: 'Development', description: 'Agile development with 2-week sprints, regular demos, and continuous integration for fast delivery.', icon: 'Code', color: '#059669' },
  { step: 5, title: 'Testing', description: 'Comprehensive automated and manual testing including performance, security, and accessibility audits.', icon: 'CheckCircle', color: '#D97706' },
  { step: 6, title: 'Deployment', description: 'Seamless deployment with zero-downtime releases, monitoring setup, and production verification.', icon: 'Rocket', color: '#0891B2' },
  { step: 7, title: 'Support', description: 'Ongoing maintenance, performance monitoring, feature enhancements, and dedicated support SLAs.', icon: 'Headphones', color: '#10B981' },
]

export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
  {
    id: 'healthtrack-pro',
    title: 'HealthTrack Pro',
    category: ['Web', 'AI'],
    industry: 'Healthcare',
    tech: ['Next.js', 'Python', 'TensorFlow', 'Azure'],
    description: 'AI-powered patient monitoring platform with real-time vitals tracking, predictive diagnostics, and telehealth capabilities.',
    metrics: [{ label: 'Patients Onboarded', value: '50K+' }, { label: 'Diagnosis Accuracy', value: '94%' }, { label: 'Cost Reduction', value: '35%' }],
    gradient: 'from-red-500 to-rose-600',
    color: '#DC2626',
  },
  {
    id: 'finflow-dashboard',
    title: 'FinFlow Dashboard',
    category: ['Web', 'Enterprise'],
    industry: 'Finance',
    tech: ['React', 'Node.js', 'PostgreSQL', 'AWS'],
    description: 'Enterprise financial analytics dashboard with real-time market data, portfolio management, and regulatory reporting.',
    metrics: [{ label: 'Assets Managed', value: '$2B+' }, { label: 'Report Generation', value: '10x faster' }, { label: 'Uptime', value: '99.99%' }],
    gradient: 'from-blue-500 to-indigo-600',
    color: '#2563EB',
  },
  {
    id: 'edunest-lms',
    title: 'EduNest LMS',
    category: ['Web', 'Mobile'],
    industry: 'Education',
    tech: ['React Native', 'Next.js', 'MongoDB', 'GCP'],
    description: 'Comprehensive learning management system with live classes, AI-personalized learning paths, and gamification.',
    metrics: [{ label: 'Active Learners', value: '200K+' }, { label: 'Course Completion', value: '78%' }, { label: 'Revenue Growth', value: '3x' }],
    gradient: 'from-violet-500 to-purple-600',
    color: '#7C3AED',
  },
  {
    id: 'shopflow-commerce',
    title: 'ShopFlow Commerce',
    category: ['Web', 'Cloud'],
    industry: 'Retail',
    tech: ['Next.js', 'Node.js', 'Redis', 'AWS'],
    description: 'Scalable e-commerce platform handling 100K+ daily transactions with personalized recommendations and omnichannel support.',
    metrics: [{ label: 'Daily Transactions', value: '100K+' }, { label: 'Page Load Speed', value: '0.8s' }, { label: 'Conversion Rate', value: '+42%' }],
    gradient: 'from-amber-500 to-orange-600',
    color: '#D97706',
  },
  {
    id: 'logictrack-supply',
    title: 'LogicTrack Supply',
    category: ['Enterprise', 'AI'],
    industry: 'Logistics',
    tech: ['React', '.NET', 'SQL Server', 'Azure'],
    description: 'AI-powered supply chain optimization platform with real-time tracking, demand forecasting, and automated routing.',
    metrics: [{ label: 'Delivery Efficiency', value: '+58%' }, { label: 'Fuel Cost Saved', value: '22%' }, { label: 'Routes Optimized', value: '1M+/day' }],
    gradient: 'from-cyan-500 to-sky-600',
    color: '#0891B2',
  },
  {
    id: 'govlink-portal',
    title: 'GovLink Citizen Portal',
    category: ['Web', 'Enterprise'],
    industry: 'Government',
    tech: ['Angular', 'Java', 'PostgreSQL', 'Azure'],
    description: 'Digital citizen services portal enabling online applications, document management, and real-time service tracking.',
    metrics: [{ label: 'Citizens Served', value: '2M+' }, { label: 'Processing Time', value: '-70%' }, { label: 'Satisfaction Score', value: '4.8/5' }],
    gradient: 'from-emerald-500 to-green-600',
    color: '#059669',
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah Mitchell',
    designation: 'Chief Technology Officer',
    company: 'NovaTech Corp',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    initials: 'SM',
    rating: 5,
    review: 'QuickMindsSolutions delivered an exceptional enterprise platform that transformed our operations. Their team\'s technical depth, communication, and commitment to quality exceeded every expectation. We\'ve seen a 40% efficiency improvement since launch.',
    color: '#2563EB',
  },
  {
    id: '2',
    name: 'James Rodriguez',
    designation: 'VP of Product',
    company: 'Apex Digital',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    initials: 'JR',
    rating: 5,
    review: 'Working with QMS on our mobile app was a game-changer. They not only built exactly what we envisioned but suggested improvements that made it 10x better. The app has 4.9 stars on the App Store with 50K+ downloads in the first month.',
    color: '#7C3AED',
  },
  {
    id: '3',
    name: 'Priya Sharma',
    designation: 'Founder & CEO',
    company: 'Horizon Labs',
    avatar: 'https://randomuser.me/api/portraits/women/28.jpg',
    initials: 'PS',
    rating: 5,
    review: 'As a startup, we needed a partner who could move fast without sacrificing quality. QMS delivered our MVP in 8 weeks, and it\'s rock solid. Their agile process kept us aligned at every step. Highly recommended for any startup looking to build right.',
    color: '#059669',
  },
  {
    id: '4',
    name: 'David Chen',
    designation: 'Director of Engineering',
    company: 'CloudPeak Inc',
    avatar: 'https://randomuser.me/api/portraits/men/50.jpg',
    initials: 'DC',
    rating: 5,
    review: 'The cloud migration QMS executed for us was flawless. Zero downtime, 60% cost reduction, and significantly improved performance. Their DevOps expertise is world-class. They\'re now our go-to partner for all infrastructure work.',
    color: '#0891B2',
  },
  {
    id: '5',
    name: 'Emily Watson',
    designation: 'Head of Digital',
    company: 'DataSphere',
    avatar: 'https://randomuser.me/api/portraits/women/62.jpg',
    initials: 'EW',
    rating: 5,
    review: 'Our AI-powered analytics platform built by QMS has become the core of our business intelligence. The machine learning models are incredibly accurate, and the team continuously improves them. Best tech investment we\'ve made.',
    color: '#D97706',
  },
  {
    id: '6',
    name: 'Michael Park',
    designation: 'COO',
    company: 'InnoVault',
    avatar: 'https://randomuser.me/api/portraits/men/41.jpg',
    initials: 'MP',
    rating: 5,
    review: 'QMS transformed our decade-old legacy system into a modern, scalable platform without disrupting operations. Their phased approach was masterful. We\'re now 3x more productive and our customers love the new experience.',
    color: '#EC4899',
  },
]

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: '1',
    name: 'Alex Thompson',
    role: 'CEO & Co-Founder',
    department: 'Leadership',
    initials: 'AT',
    color: '#2563EB',
    linkedin: 'https://linkedin.com',
    bio: '15+ years in enterprise software. Former engineering lead at Fortune 500 companies.',
    skills: ['Strategy', 'Enterprise Architecture', 'Leadership'],
  },
  {
    id: '2',
    name: 'Rachel Kim',
    role: 'CTO & Co-Founder',
    department: 'Leadership',
    initials: 'RK',
    color: '#7C3AED',
    linkedin: 'https://linkedin.com',
    bio: 'Cloud architect and AI specialist with patents in distributed systems.',
    skills: ['Cloud Architecture', 'AI/ML', 'Distributed Systems'],
  },
  {
    id: '3',
    name: 'Marcus Johnson',
    role: 'VP of Engineering',
    department: 'Engineering',
    initials: 'MJ',
    color: '#059669',
    linkedin: 'https://linkedin.com',
    bio: 'Full-stack expert who has shipped products used by millions worldwide.',
    skills: ['React', 'Node.js', 'System Design'],
  },
  {
    id: '4',
    name: 'Sofia Martinez',
    role: 'Head of Design',
    department: 'Design',
    initials: 'SM',
    color: '#EC4899',
    linkedin: 'https://linkedin.com',
    bio: 'Award-winning UX designer with expertise in design systems and user research.',
    skills: ['UX Research', 'Design Systems', 'Figma'],
  },
  {
    id: '5',
    name: 'Daniel Lee',
    role: 'Lead Cloud Architect',
    department: 'Engineering',
    initials: 'DL',
    color: '#0891B2',
    linkedin: 'https://linkedin.com',
    bio: 'AWS & Azure certified architect specializing in enterprise cloud migrations.',
    skills: ['AWS', 'Azure', 'DevOps', 'Terraform'],
  },
  {
    id: '6',
    name: 'Aisha Patel',
    role: 'AI/ML Lead',
    department: 'Engineering',
    initials: 'AP',
    color: '#D97706',
    linkedin: 'https://linkedin.com',
    bio: 'PhD in Machine Learning. Led AI initiatives for healthcare and fintech clients.',
    skills: ['TensorFlow', 'PyTorch', 'NLP', 'Computer Vision'],
  },
  {
    id: '7',
    name: 'Tom Bradley',
    role: 'Head of Sales',
    department: 'Management',
    initials: 'TB',
    color: '#4F46E5',
    linkedin: 'https://linkedin.com',
    bio: 'Enterprise sales expert who has closed deals with 50+ Fortune 500 companies.',
    skills: ['Enterprise Sales', 'Account Management', 'CRM'],
  },
  {
    id: '8',
    name: 'Nina Okafor',
    role: 'QA & Testing Lead',
    department: 'Engineering',
    initials: 'NO',
    color: '#DC2626',
    linkedin: 'https://linkedin.com',
    bio: 'Quality champion who has built automation frameworks that saved millions in bugs.',
    skills: ['Selenium', 'Playwright', 'Test Architecture'],
  },
]

export const FAQS: FAQ[] = [
  {
    id: '1',
    question: 'How long does it typically take to build a web application?',
    answer: 'Timeline varies based on complexity. A typical MVP takes 8–12 weeks, a mid-size application 3–6 months, and enterprise-grade solutions 6–12+ months. We provide a detailed timeline during the discovery phase after understanding your specific requirements.',
  },
  {
    id: '2',
    question: 'What technologies do you specialize in?',
    answer: 'We specialize in modern tech stacks including React, Next.js, Node.js, .NET, Java, Python for development; AWS, Azure, GCP for cloud; Docker and Kubernetes for DevOps; and TensorFlow/PyTorch for AI/ML. We choose the right technology based on your project needs.',
  },
  {
    id: '3',
    question: 'Do you provide ongoing maintenance and support after launch?',
    answer: 'Absolutely. We offer flexible post-launch support packages including 24/7 monitoring, regular security updates, performance optimization, bug fixes, and feature enhancements. Our SLAs guarantee response times based on severity levels.',
  },
  {
    id: '4',
    question: 'How do you handle project communication and updates?',
    answer: 'We use a transparent communication model with dedicated project managers, daily standups, weekly demos, and a shared project dashboard. You\'ll have real-time visibility into progress via Jira or equivalent tools, and direct access to your development team.',
  },
  {
    id: '5',
    question: 'What is your pricing model?',
    answer: 'We offer multiple engagement models: Fixed Price (for well-defined projects), Time & Material (for evolving requirements), Dedicated Team (for ongoing development), and Retainer (for maintenance). We provide detailed proposals with no hidden costs.',
  },
  {
    id: '6',
    question: 'Can you work with our existing codebase or systems?',
    answer: 'Yes, we excel at working with legacy systems. We perform thorough code audits, identify improvement areas, and can either incrementally modernize or do a full rebuild depending on what\'s best for your business and budget.',
  },
  {
    id: '7',
    question: 'How do you ensure the security of my application?',
    answer: 'Security is built into our development process from day one. We follow OWASP Top 10 guidelines, conduct regular security audits, implement CSP headers, use encryption for data at rest and in transit, and offer penetration testing services.',
  },
  {
    id: '8',
    question: 'Do you sign NDAs and protect intellectual property?',
    answer: 'Yes, we sign comprehensive NDAs before any project discussion. All intellectual property developed is fully transferred to you upon project completion. We use secure development environments and follow strict data protection protocols.',
  },
  {
    id: '9',
    question: 'Can you scale up or down the team as needed?',
    answer: 'Absolutely. One of our core strengths is flexibility. We can scale team size within 2 weeks — adding specialists or reducing scope based on your evolving business needs, ensuring you only pay for what you need.',
  },
  {
    id: '10',
    question: 'What industries do you have experience in?',
    answer: 'We have deep expertise across healthcare, finance, education, retail, logistics, government, manufacturing, hospitality, insurance, real estate, travel, and telecommunications. Industry-specific experience ensures we understand your unique compliance and workflow needs.',
  },
  {
    id: '11',
    question: 'How do you handle cloud migration projects?',
    answer: 'We follow a structured 5-phase migration approach: Assessment, Planning, Proof of Concept, Migration, and Optimization. We minimize downtime using blue-green deployments and ensure zero data loss. Our migrations typically achieve 30–60% cost reduction.',
  },
  {
    id: '12',
    question: 'Do you build mobile apps for both iOS and Android?',
    answer: 'Yes. We develop for both platforms using React Native or Flutter for cross-platform (sharing 85–90% code), or native Swift (iOS) and Kotlin (Android) when maximum performance is required. We also handle App Store and Play Store submissions.',
  },
  {
    id: '13',
    question: 'What sets QuickMindsSolutions apart from other IT companies?',
    answer: 'Our differentiators: 12+ years of enterprise experience, a rigorous hiring process (top 5% of engineers), dedicated project ownership, transparent communication, and a proven track record with 500+ successful projects across 20+ countries.',
  },
  {
    id: '14',
    question: 'Can you help with UI/UX design for an existing application?',
    answer: 'Yes. We provide UX audits, user research, wireframing, prototyping, and redesign services. We start with data — user behavior analytics, heatmaps, and interviews — to make informed design decisions that improve key metrics.',
  },
  {
    id: '15',
    question: 'How do I get started with QuickMindsSolutions?',
    answer: 'Simply reach out via our contact form or book a free 30-minute consultation. We\'ll discuss your project, provide initial feedback, and propose a discovery engagement. Most projects kick off within 2 weeks of initial contact.',
  },
]

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'The Future of AI in Enterprise Software: Trends for 2025',
    excerpt: 'Explore how generative AI, autonomous agents, and large language models are reshaping enterprise software and creating new opportunities for businesses.',
    category: 'AI',
    author: 'Aisha Patel',
    authorInitials: 'AP',
    authorColor: '#D97706',
    date: 'Jun 28, 2025',
    readTime: '8 min read',
    gradient: 'from-emerald-500 to-teal-600',
    tags: ['AI', 'Enterprise', 'LLM', 'Automation'],
  },
  {
    id: '2',
    title: 'Building Scalable Microservices with Node.js and Kubernetes',
    excerpt: 'A deep-dive into architecting production-ready microservices — service discovery, circuit breakers, distributed tracing, and zero-downtime deployments.',
    category: 'Development',
    author: 'Marcus Johnson',
    authorInitials: 'MJ',
    authorColor: '#059669',
    date: 'Jun 18, 2025',
    readTime: '12 min read',
    gradient: 'from-blue-500 to-indigo-600',
    tags: ['Microservices', 'Node.js', 'Kubernetes', 'Docker'],
  },
  {
    id: '3',
    title: 'Cloud Cost Optimization: 10 Strategies That Actually Work',
    excerpt: 'Practical, actionable strategies to reduce your AWS and Azure bills by 30–50% without sacrificing performance, reliability, or security.',
    category: 'Cloud',
    author: 'Daniel Lee',
    authorInitials: 'DL',
    authorColor: '#0891B2',
    date: 'Jun 10, 2025',
    readTime: '10 min read',
    gradient: 'from-cyan-500 to-sky-600',
    tags: ['Cloud', 'AWS', 'Azure', 'Cost Optimization'],
  },
  {
    id: '4',
    title: 'Why Your Digital Transformation Is Failing (And How to Fix It)',
    excerpt: 'Most digital transformation initiatives fail due to people, not technology. Learn the proven frameworks for driving successful organizational change.',
    category: 'Digital Transformation',
    author: 'Alex Thompson',
    authorInitials: 'AT',
    authorColor: '#2563EB',
    date: 'May 30, 2025',
    readTime: '9 min read',
    gradient: 'from-red-500 to-orange-600',
    tags: ['Digital Transformation', 'Strategy', 'Leadership'],
  },
  {
    id: '5',
    title: 'Next.js 14 Server Components: A Complete Production Guide',
    excerpt: 'Everything you need to know about React Server Components in Next.js 14 — data fetching patterns, caching strategies, and performance optimization.',
    category: 'Technology',
    author: 'Rachel Kim',
    authorInitials: 'RK',
    authorColor: '#7C3AED',
    date: 'May 20, 2025',
    readTime: '15 min read',
    gradient: 'from-violet-500 to-purple-600',
    tags: ['Next.js', 'React', 'Server Components', 'Performance'],
  },
  {
    id: '6',
    title: 'DevSecOps: Embedding Security Into Your CI/CD Pipeline',
    excerpt: 'Learn how to integrate SAST, DAST, dependency scanning, and secret detection into your deployment pipeline for continuous security assurance.',
    category: 'Cyber Security',
    author: 'Nina Okafor',
    authorInitials: 'NO',
    authorColor: '#DC2626',
    date: 'May 8, 2025',
    readTime: '11 min read',
    gradient: 'from-slate-600 to-gray-700',
    tags: ['Security', 'DevSecOps', 'CI/CD', 'OWASP'],
  },
]

export const CAREER_POSITIONS: CareerPosition[] = [
  {
    id: '1',
    title: 'Senior Full-Stack Engineer',
    department: 'Engineering',
    location: 'Remote / San Francisco',
    type: 'Full-time',
    experience: '5+ years',
    description: 'Build scalable web applications for enterprise clients using React, Node.js, and cloud technologies.',
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'AWS'],
  },
  {
    id: '2',
    title: 'Lead AI/ML Engineer',
    department: 'Engineering',
    location: 'Remote',
    type: 'Full-time',
    experience: '6+ years',
    description: 'Lead development of AI-powered solutions including NLP, computer vision, and predictive analytics.',
    skills: ['Python', 'TensorFlow', 'PyTorch', 'MLOps', 'LLM'],
  },
  {
    id: '3',
    title: 'Senior UX Designer',
    department: 'Design',
    location: 'Hybrid / New York',
    type: 'Full-time',
    experience: '4+ years',
    description: 'Own end-to-end design for complex enterprise products — from user research to polished UI.',
    skills: ['Figma', 'User Research', 'Design Systems', 'Prototyping'],
  },
  {
    id: '4',
    title: 'Cloud Solutions Architect',
    department: 'Engineering',
    location: 'Remote',
    type: 'Full-time',
    experience: '7+ years',
    description: 'Design and oversee cloud architecture for enterprise-scale migrations and greenfield projects.',
    skills: ['AWS', 'Azure', 'Terraform', 'Kubernetes', 'Architecture'],
  },
  {
    id: '5',
    title: 'DevOps Engineer',
    department: 'Engineering',
    location: 'Remote',
    type: 'Full-time',
    experience: '4+ years',
    description: 'Build and maintain CI/CD pipelines, container infrastructure, and observability platforms.',
    skills: ['Docker', 'Kubernetes', 'GitHub Actions', 'Terraform', 'Prometheus'],
  },
  {
    id: '6',
    title: 'Business Development Manager',
    department: 'Sales',
    location: 'San Francisco / New York',
    type: 'Full-time',
    experience: '5+ years',
    description: 'Drive enterprise sales, build client relationships, and close deals for IT solutions and consulting.',
    skills: ['Enterprise Sales', 'Salesforce', 'Negotiation', 'Proposals'],
  },
]

export const AWARDS: Award[] = [
  { title: 'ISO 9001:2015 Certified', year: '2024', issuer: 'ISO', icon: 'Award', color: '#D97706' },
  { title: 'Microsoft Solutions Partner', year: '2024', issuer: 'Microsoft', icon: 'Star', color: '#2563EB' },
  { title: 'AWS Advanced Partner', year: '2023', issuer: 'Amazon Web Services', icon: 'Cloud', color: '#F59E0B' },
  { title: 'Google Cloud Partner', year: '2023', issuer: 'Google', icon: 'Globe', color: '#059669' },
  { title: 'Top Software Developer', year: '2024', issuer: 'Clutch.co', icon: 'Trophy', color: '#7C3AED' },
  { title: 'Best Tech Company', year: '2023', issuer: 'Goodfirms', icon: 'Medal', color: '#EC4899' },
]
